name = "tt-leaderboard-worker-1-dev"
type = "javascript"
account_id = "589927a35e1fe7c2cadbdb3bc6d2db75"
zone_id = "58a51453c62c5b66f8568340bd0462eb"
compatibility_date = "2021-11-02"
workers_dev = true

[build]
command = "yarn && yarn webpack"
[build.upload]
format = "service-worker"

[env.production]
name = "tt-leaderboard-worker-1-prod"
type = "webpack"
route = "tt-leaderboard.takayamasan.dev/api"

kv_namespaces = [
  { binding = "NAMESPACE", id = "45535816551a4ee98eadf251bd3367bf" }
]
